# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
    rate_limiter:
        test:
            # use 'sliding_window' if you prefer that policy
            policy: 'sliding_window'
            limit: 10000
            interval: '60 minutes'
            cache_pool: 'rate_limit.pool'
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
